export class Hospital {
  constructor(
    public slug: string = '',
    public name: string = '',
    public address1: string = '',
    public address2: string = '',
    public city: string = '',
    public state: string = '',
    public postalCode: string = '',
    public phone: string = '',
    public isCovid: boolean = true,
    public bedCapacity: number = 0,
    public bedsInUse: number = 0,
    public percentOfUsage: number = 0,
    public createdOn: string = '',
    public updatedOn: string = '',
    public regionId: string = '',
    public regionName: string = '',
    public region?: any,
    public id?: string,
    public capacity1: number = 0,
    public capacity2: number = 0,
    public capacity3: number = 0,
    public capacity4: number = 0,
    public capacity5: number = 0,
    public capacity6: number = 0,
    public capacity7: number = 0,
    public capacity8: number = 0,
    public capacity9: number = 0,
    public capacity10: number = 0,
    public used1: number = 0,
    public used2: number = 0,
    public used3: number = 0,
    public used4: number = 0,
    public used5: number = 0,
    public used6: number = 0,
    public used7: number = 0,
    public used8: number = 0,
    public used9: number = 0,
    public used10: number = 0
  ) {}
}
